name: News Bot Auto Run

on:
  schedule:
    # සෑම විනාඩි 15කට වරක් ස්වයංක්‍රීයව ක්‍රියාත්මක වීමට (Every 15 minutes)
    - cron: '*/15 * * * *'
  workflow_dispatch: # අපට අවශ්‍ය වෙලාවට manual රන් කිරීමට

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4 newspaper3k deep_translator lxml_html_clean schedule flask

      - name: Run Python Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
